language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t tmcmilla/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tmcmilla/docker-react npm run test
  